export declare const CURSOR_SDK_EVENT_DEBUG_ENV: "PI_CURSOR_SDK_EVENT_DEBUG";
export declare const CURSOR_SDK_EVENT_DEBUG_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_RUN_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_RUN_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_SESSION_DIR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_SESSION_DIR";
export declare const CURSOR_SDK_EVENT_DEBUG_STDERR_ENV: "PI_CURSOR_SDK_EVENT_DEBUG_STDERR";
export declare const CURSOR_SDK_EVENT_DEBUG_ENV_NAMES: readonly [
	typeof CURSOR_SDK_EVENT_DEBUG_ENV,
	typeof CURSOR_SDK_EVENT_DEBUG_DIR_ENV,
	typeof CURSOR_SDK_EVENT_DEBUG_RUN_DIR_ENV,
	typeof CURSOR_SDK_EVENT_DEBUG_SESSION_DIR_ENV,
	typeof CURSOR_SDK_EVENT_DEBUG_STDERR_ENV,
];
