#!/usr/bin/env tsx
/**
 * Fetches models from the Ollama Cloud API and writes them to
 * models.generated.ts. Run manually and commit the output when
 * the model catalog changes.
 *
 * Usage:
 *   npm install  # ensure tsx is available
 *   npm run generate-models
 */

import { writeFileSync } from "node:fs";
import { assembleModels, refreshOllamaCloudModels } from "../models.ts";

// Models announced for retirement by Ollama (effective 2026-06-16):
// https://docs.ollama.com/cloud#deprecations. Excluded from the generated
// list so we don't ship support for them by default, but
// `/ollama-cloud-refresh` will still surface them until they are fully
// removed from the API.
const RETIRED_MODEL_IDS = new Set<string>([
  "kimi-k2-thinking",
  "kimi-k2:1t",
  "minimax-m2",
  "glm-4.6",
  "qwen3-next:80b",
  "qwen3-vl:235b",
  "qwen3-vl:235b-instruct",
  "cogito-2.1:671b",
]);

console.log("Fetching Ollama Cloud models...");
const raw = await refreshOllamaCloudModels({
  notify: (msg) => console.log(`  ${msg}`),
  onProgress: (p) => {
    if (p.stage === "details" && p.total) {
      process.stdout.write(`\r  ${p.current}/${p.total} models fetched...`);
    }
  },
});

const assembled = assembleModels(raw);
const models = assembled.filter((m) => !RETIRED_MODEL_IDS.has(m.id));
const retired = assembled.length - models.length;
console.log(
  `\nAssembled ${assembled.length} tool-capable models (${retired} retired, ${models.length} shipped).`,
);

// Stable serialization: sort models by id and object keys so field order
// changes in the source don't produce gratuitous diffs. `id` and `name`
// come first to make it easy to spot a model in the generated file.
const PREFERRED_KEYS = ["id", "name"];
function sortKeys(obj: unknown): unknown {
  if (obj && typeof obj === "object" && !Array.isArray(obj)) {
    return Object.keys(obj)
      .sort((a, b) => {
        const ai = PREFERRED_KEYS.indexOf(a);
        const bi = PREFERRED_KEYS.indexOf(b);
        if (ai !== -1 && bi !== -1) return ai - bi;
        if (ai !== -1) return -1;
        if (bi !== -1) return 1;
        return a < b ? -1 : a > b ? 1 : 0;
      })
      .reduce(
        (sorted, k) => {
          sorted[k] = sortKeys((obj as Record<string, unknown>)[k]);
          return sorted;
        },
        {} as Record<string, unknown>,
      );
  }
  if (Array.isArray(obj)) return obj.map(sortKeys);
  return obj;
}

const sortedModels = [...models].sort((a, b) => {
  const aid = a.id ?? "";
  const bid = b.id ?? "";
  return aid < bid ? -1 : aid > bid ? 1 : 0;
});

const out = [
  "// Auto-generated by scripts/generate-models.ts",
  "// Do not edit manually.",
  `// Generated: ${new Date().toISOString()}`,
  `// Model count: ${models.length}`,
  "",
  'import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";',
  "",
  "export const GENERATED_MODELS: ProviderModelConfig[] = ",
  `${JSON.stringify(sortKeys(sortedModels), null, 2)};`,
  "",
].join("\n");

writeFileSync("models.generated.ts", out);
console.log(`Wrote models.generated.ts (${models.length} models).`);
